"""initial schema

Revision ID: 10cb15d06661
Revises: 
Create Date: 2026-09-20 20:18:14.972925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cb15d06661'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('article_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('part_title', sa.String(length=255), nullable=False),
    sa.Column('difficulty_score', sa.Integer(), nullable=False),
    sa.Column('estimated_xp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_part_number'), 'articles', ['part_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('article_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.String(length=10), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', name='uq_dependency_pair')
    )
    op.create_index(op.f('ix_article_dependencies_source_id'), 'article_dependencies', ['source_id'], unique=False)
    op.create_index(op.f('ix_article_dependencies_target_id'), 'article_dependencies', ['target_id'], unique=False)
    op.create_table('clauses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=10), nullable=False),
    sa.Column('clause_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clauses_article_id'), 'clauses', ['article_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=10), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('knowledge_type', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_article_id'), 'quiz_questions', ['article_id'], unique=False)
    op.create_table('user_article_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='uq_user_article')
    )
    op.create_index(op.f('ix_user_article_progress_article_id'), 'user_article_progress', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_article_progress_user_id'), 'user_article_progress', ['user_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_question_id'), 'quiz_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('sub_clauses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_clauses_clause_id'), 'sub_clauses', ['clause_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_clauses_clause_id'), table_name='sub_clauses')
    op.drop_table('sub_clauses')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_question_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_user_article_progress_user_id'), table_name='user_article_progress')
    op.drop_index(op.f('ix_user_article_progress_article_id'), table_name='user_article_progress')
    op.drop_table('user_article_progress')
    op.drop_index(op.f('ix_quiz_questions_article_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_clauses_article_id'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_article_dependencies_target_id'), table_name='article_dependencies')
    op.drop_index(op.f('ix_article_dependencies_source_id'), table_name='article_dependencies')
    op.drop_table('article_dependencies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_articles_part_number'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###