"""add hearts and leagues, boolean flag

Revision ID: cc1dc85a5755
Revises: 10cb15d06661
Create Date: 2026-09-20 20:22:39.895532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1dc85a5755'
down_revision: Union[str, None] = '10cb15d06661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hearts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hearts_left', sa.Integer(), nullable=False),
    sa.Column('max_hearts', sa.Integer(), nullable=False),
    sa.Column('last_refill_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start', 'user_id', name='uq_league_week_user')
    )
    op.create_index(op.f('ix_leagues_user_id'), 'leagues', ['user_id'], unique=False)
    op.alter_column('quiz_attempts', 'is_correct',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               postgresql_using='is_correct::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_attempts', 'is_correct',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='is_correct::int')
    op.drop_index(op.f('ix_leagues_user_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('hearts')
    # ### end Alembic commands ###